### ISSUE TITLE
code review 1 by Lucas Eddy

### ISSUE THREAD

**Issue by ghost** [jholmquest/IndieProject#3]
@jholmquest 

https://github.com/radagon828/IndieProjectLucasE/blob/master/Code%20Reviews/jholmquestReview.md

**Comment by ghost** [comment]
@pawaitemadisoncollege

**Comment by pawaitemadisoncollege** [comment]
@radagon828 Please paste the review markdown directly in this issue as shown in class, rather than storing it in your indie project. (The video is available in slack). Thanks!

**Comment by ghost** [comment]
# Design/Code Review 1
​
## Project:
​Insect Collection Helper
### Developer:
​ James Holmquest
### Reviewer:
​Lucas Eddy

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. EVERY item should have *at least* one "kudos" and one suggestion for improvement|
|**Problem Statement**|1. Accurately describes the project's purpose.<br> 2. Is professional and free of typos, slang, etc.<br> 3. Thoroughly explains the problem and the solution.<br> 4. Is understandable by the average person.|I understand that your website will allow the recording of bug information but I don't understand the problem that it will solve. Also While I can assume that your website will allow the creation of accounts in order to use its features that and the details of how it may work are not clear. Do users keep a personal collection with their own labels, will they be able to share what they have found? |
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens. <br>5. Project plan and time log are up-to-date. |Maybe have a screen shot for the advanced form field entry. I really like your time log you seem to be very good at keeping track of your work, Your plan is built around the checkpoints which is responsible. I'm unsure if your user stories cover all functionality intended for your website, shouldn't their be a user story for storing the location where you found an insect? |
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model. <br> 2. There are at least two 1-to-many relationships.<br> 3. The model represents good database design. <br>|I don't have a database model myself so this is difficult for me to commment on. From what I understand their is a one to many relationship between users and specimen.  |
|**Code**|1. Proper Maven project structure is used. <br> 2. a .gitignore file for IntelliJ Java projects has been implemented. <br> 3. There is not any redundant or copy/paste code in the JSPs or classes.<br> 4. Classes are appropriately-sized (no monster classes).<br> Property files are used appropriately: no hard-coded values. <br> 5. Logging statements are used rather than System.out.println and printStackTrace (be sure to use a search to look for these!).<br> 6. There are appropriate unit tests/code coverage.| I can't say much as many of your planned classes and jsps don't seem to be their yet. many of the classes you do have seem to be compelte with hibernate annotations and all. I look forward to seeing how it will shape up in the future.|

**Comment by ghost** [comment]
@jholmquest

**Comment by pawaitemadisoncollege** [comment]
@radagon828 and @jholmquest  One thing to add to this, there are some sneaky System.out.printlns out there.  Don't you love it when instructor-provided code has built-in standards "

![Screen Shot 2021-02-26 at 10 57 53 AM](https://user-images.githubusercontent.com/13874466/109330691-9260bf80-7821-11eb-97b2-5525690aea3e.png)
