### ISSUE TITLE
Week 6 ready for review

### ISSUE THREAD

**Issue by jholmquest** [jholmquest/IndieProject#5]
@pawaitemadisoncollege got it up on aws, barebones at the moment but I wanted to use my indie project for it in case there was some troubleshooting. [Here is the link to it](http://3.142.33.172:8080/IndieProject/). The test link will take you to a page showing some users. Tested the link using data on my phone so you should be able to access it.

Since I took advanced PHP last semester my main takeaway was probably the differences in deploying a PHP project vs a Java one. Also to actually verify that I could access the AMI before the last day.

The main challenge was making sure I got all the configurations correct. I had to go back and edit the context.xml a couple times to get it right so I could deploy properly. I also initially had the db error a couple other people had, initially only created the user table, had to create the tables linked to it as well.

As previously mentioned I had an error related to my database that I solved thanks to LeeAnn Jakel's question under week 6. There was also that problem with student accounts being weird, luckily I had a backup account already setup so that was pretty easy to solve by messaging you the new ID

This week I should be able to get a lot done with my project, past couple weeks have been a little busy but I should have a bit of a breather for the next couple. I'll have the genericdao figured out and the rest of my db for the mvp built up for that checkpoint.

**Comment by pawaitemadisoncollege** [comment]
Great job getting your indie project out there! I was able to access it no problem so you have the right port open to the right IPs.

Looking forward to seeing what's new with your indie project later this week!
