### ISSUE TITLE
Checkpoint 2

### ISSUE THREAD

**Issue by jholmquest** [jholmquest/IndieProject#6]
@pawaitemadisoncollege I believe I have everything set up for the checkpoint. It's all under the Week7Work branch. Under planning ERD.png is a more detailed diagram, while db.png shows potential stretch tables. There's a screenshot in the screenshots folder showing tests passing. Many to Many was tough but I was able to figure it out thanks to https://www.baeldung.com/hibernate-many-to-many

**Comment by pawaitemadisoncollege** [comment]
You've done such a good job adding our weekly tech and learning right into your project, so you likely hit CP2 weeks ago! 

Thank you for keeping everything in your repo so organized. It's always easy to find what I'm looking for. Glad to see you are making effective use of branches too.

No nitpicks at this point :)
