### ISSUE TITLE
Week 7 ready

### ISSUE THREAD

**Issue by jholmquest** [jholmquest/IndieProject#7]
@pawaitemadisoncollege week 7 should be good, have it on the main branch

One takeaway is this seems a lot simpler than setting up authentication in php. The configurations need to be right but I don't have to do every part manually by myself.

One struggle was finding that mysql file, ended up finding it by digging through the intellij configurations to get the path that way. Otherwise main struggle was getting correct values in the config. Also had an error due to my hibernate configuration. Turns out my test config had everything right and it was only the main. Didn't notice at first due to that, since I've been mostly testing until now.

Solved the hibernate config issue with the help of [this](https://stackoverflow.com/questions/32123723/many-to-one-attribute-type-should-not-be-persistence-entity) post. Solved configuration issues from following your advice in Heather's question in week 7, as I had a similar error.

Deployed version is not up to date with login yet, plan to get that setup along with this week's work

**Comment by pawaitemadisoncollege** [comment]
You have a good start with auth here @jholmquest.  The key thing to remember going forward is that as you add more jsps and servlets, make sure they are "locked down" if needed.
