### ISSUE TITLE
Week 8 Ready

### ISSUE THREAD

**Issue by jholmquest** [jholmquest/IndieProject#8]
@pawaitemadisoncollege Got my api up and running a little early since spring break is around the corner. On the api_initial branch.

My big takeaway is to read the documentation carefully when using an api. If I do that things go pretty smoothly.

The main challenge this week for me was formatting my url properly. I misread the documentation at first and thought my api was using the % symbol as a space, not noticing that every % had a 20 after it. Also had to do some digging through classes to figure out how to access the results I wanted, as the json I got back had several layers to it.

One source I referred back to a lot was the [google geocoding documentation](https://developers.google.com/maps/documentation/geocoding/overview). There's a lot in there so I made sure to bookmark it for easy access. [This](https://stackoverflow.com/questions/48780583/malformed-escape-pair-at-index-103-http-localhost8025-oauth2db-oauth-tokeng) post on stackoverflow also helped put me on the right path as that was the error I was getting.

Definitely going to experiment a little with the json I'm getting back to see if I can do something useful with some of the stuff beyond lat and long. Might be able to use the bounds to calculate where to round the coordinates to.

**Comment by pawaitemadisoncollege** [comment]
Nice job getting the api working. Next step is to great a dao or similar class for this business: https://github.com/jholmquest/IndieProject/blob/4a872031626f4126694ff6c6e7bd88bd717ac0f0/src/test/java/bugnet/api/GeocoderTest.java#L19-L24.

Glad to see you are using properties already too!
