### ISSUE TITLE
Checkpoint 3

### ISSUE THREAD

**Issue by jholmquest** [jholmquest/IndieProject#9]
@pawaitemadisoncollege login now up and working the deployed version of the application. Currently user creation has not been enabled, login with username: master and password: password69 (I know, not very secure, will make things more secure when there's actual access to information). URL is http://3.142.33.172:8080/IndieProject

Everything's on the main branch now, excited to do more coding now that things have been configured

**Comment by jholmquest** [comment]
oh yeah, since I didn't really specify, click on test to get the login prompt if you're not already logged in

**Comment by pawaitemadisoncollege** [comment]
Nice job hitting CP3 @jholmquest. You have a good foundation here, and are in a good position to begin building out the various fun parts of your application now! Looking forward to seeing some of those buggy (in a good way) pages in the coming weeks!
